project:
  type: website

website:
  title: "Prueba de Concepto CA"
  favicon: favicon-32x32.png
  navbar:
    left:
      - text: "PDC"
        href: lista_de_precios_ca_tio_central.qmd
      - text: "Presentación"
        href: propuesta_de_colaboracion.qmd

format:
  html:
    theme: default
    toc: true